"use client";

import { BatteryCharging, Car, Home, Sun, Zap } from "lucide-react";
import type { CustomerDevice } from "@/lib/api/types";
import { cn, formatPercent, formatPower } from "@/lib/utils";

const GENERATION_KINDS = new Set(["solar", "wind", "wind_turbine"]);

export interface DeviceFlows {
  /** kW generated by solar/wind devices (≥ 0). */
  generation: number;
  /** kW into batteries (≥ 0). */
  batteryCharging: number;
  /** kW out of batteries (≥ 0). */
  batteryDischarging: number;
  /** kW drawn by other metered devices (EV chargers, heat pumps, …; ≥ 0). */
  deviceLoad: number;
  /**
   * Net kW the devices supply to the home/grid (negative = they draw from
   * the home/grid). Household consumption is not metered, so this is not the
   * grid import/export at the meter.
   */
  netSupply: number;
  /** Mean SOC (0–1) over batteries reporting one, else null. */
  batterySoc: number | null;
  online: number;
  offline: number;
  hasGeneration: boolean;
  hasBattery: boolean;
  hasLoads: boolean;
}

/**
 * Aggregate live device power into flows. Sign convention (backend
 * `device_state`): + charging/consuming, − discharging; generation devices
 * report their output as a positive number (abs() guards against meters
 * that report generation as negative).
 */
export function deviceFlows(devices: CustomerDevice[]): DeviceFlows {
  const f: DeviceFlows = {
    generation: 0,
    batteryCharging: 0,
    batteryDischarging: 0,
    deviceLoad: 0,
    netSupply: 0,
    batterySoc: null,
    online: 0,
    offline: 0,
    hasGeneration: false,
    hasBattery: false,
    hasLoads: false,
  };
  const socs: number[] = [];
  for (const d of devices) {
    const kind = d.kind.toLowerCase();
    if (GENERATION_KINDS.has(kind)) f.hasGeneration = true;
    else if (kind === "battery") f.hasBattery = true;
    else if (kind !== "thermostat") f.hasLoads = true;

    if (d.online === false) {
      f.offline += 1;
      continue;
    }
    f.online += 1;
    const p = Number(d.current_power ?? 0);
    if (!Number.isFinite(p)) continue;
    if (GENERATION_KINDS.has(kind)) {
      f.generation += Math.abs(p);
    } else if (kind === "battery") {
      if (p >= 0) f.batteryCharging += p;
      else f.batteryDischarging += -p;
      if (d.state_of_charge != null) socs.push(d.state_of_charge);
    } else if (p > 0) {
      f.deviceLoad += p;
    } else {
      // A device exporting (e.g. V2H) counts as supply.
      f.generation += -p;
    }
  }
  f.netSupply = f.generation + f.batteryDischarging - f.batteryCharging - f.deviceLoad;
  f.batterySoc = socs.length ? socs.reduce((a, b) => a + b, 0) / socs.length : null;
  return f;
}

export function EnergyFlow({ devices }: { devices: CustomerDevice[] }) {
  const f = deviceFlows(devices);
  const empty = devices.length === 0;

  return (
    <div
      role="figure"
      aria-labelledby="energy-flow-title"
      data-testid="energy-flow"
      className="rounded-md border bg-card p-4"
    >
      <h3 id="energy-flow-title" className="mb-3 text-sm font-semibold">
        Energy right now
      </h3>
      {empty ? (
        <p className="text-sm text-muted-foreground">
          No devices are linked to your account yet, so there is no live power to show.
        </p>
      ) : (
        <>
          <ul className="grid grid-cols-2 gap-3 text-center sm:grid-cols-4">
            {f.hasGeneration && (
              <Node
                icon={<Sun className="h-6 w-6" />}
                label="Solar"
                value={formatPower(f.generation)}
                detail={f.generation > 0.05 ? "generating" : "idle"}
                tone="amber"
                testId="flow-generation"
              />
            )}
            {f.hasBattery && (
              <Node
                icon={<BatteryCharging className="h-6 w-6" />}
                label="Battery"
                value={
                  f.batteryDischarging > f.batteryCharging
                    ? formatPower(f.batteryDischarging - f.batteryCharging)
                    : formatPower(f.batteryCharging - f.batteryDischarging)
                }
                detail={
                  [
                    f.batteryDischarging - f.batteryCharging > 0.05
                      ? "discharging"
                      : f.batteryCharging - f.batteryDischarging > 0.05
                        ? "charging"
                        : "idle",
                    f.batterySoc != null ? `${formatPercent(f.batterySoc)} full` : null,
                  ]
                    .filter(Boolean)
                    .join(" · ")
                }
                tone="emerald"
                testId="flow-battery"
              />
            )}
            {f.hasLoads && (
              <Node
                icon={<Car className="h-6 w-6" />}
                label="EV & loads"
                value={formatPower(f.deviceLoad)}
                detail={f.deviceLoad > 0.05 ? "drawing" : "idle"}
                tone="muted"
                testId="flow-load"
              />
            )}
            <Node
              icon={f.netSupply >= 0 ? <Home className="h-6 w-6" /> : <Zap className="h-6 w-6" />}
              label={f.netSupply >= 0 ? "To home / grid" : "From home / grid"}
              value={formatPower(Math.abs(f.netSupply))}
              detail="net of your devices"
              tone="primary"
              testId="flow-net"
            />
          </ul>
          <p className="mt-3 text-xs text-muted-foreground">
            From live readings of {f.online} online device{f.online === 1 ? "" : "s"}
            {f.offline > 0 ? ` (${f.offline} offline, not counted)` : ""}. Your home&apos;s
            total consumption isn&apos;t metered here, so the split between home and grid
            isn&apos;t shown.
          </p>
        </>
      )}
    </div>
  );
}

function Node({
  icon,
  label,
  value,
  detail,
  tone,
  testId,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  detail?: string;
  tone: "amber" | "emerald" | "primary" | "muted";
  testId?: string;
}) {
  const cls = {
    amber: "bg-amber-100 text-amber-700",
    emerald: "bg-emerald-100 text-emerald-700",
    primary: "bg-primary/10 text-primary",
    muted: "bg-muted text-foreground",
  }[tone];
  return (
    <li className="flex flex-col items-center gap-1.5" data-testid={testId}>
      <div className={cn("grid h-12 w-12 place-items-center rounded-full", cls)} aria-hidden="true">
        {icon}
      </div>
      <span className="text-xs font-medium">{label}</span>
      <span className="text-sm font-semibold tabular-nums">{value}</span>
      {detail && <span className="text-[11px] text-muted-foreground">{detail}</span>}
    </li>
  );
}
